Added CentralScene CommandClass
genielabs/zwave-lib-dotnet pull request #15
Opened 2017-05-08 17:35 UTC by bluewalk

2017-06-12 11:27 UTC, bluewalk commented
I've resolved the issues and changed to UtcNow as requested :-)

2017-06-12 11:40 UTC, genemars requested changes

2017-06-12 11:40 UTC, genielabs commented on README.md
> +
If the intention is to merge into the main repo, this note should be here. Also removal of NLog is not a good thing. There are other projects already using this library that also relay on NLog.
So adding *CentralScene CommandClass* is ok as long the PR doesn't involve structural changes to the ZWaveLib project that have not been discussed.

2017-06-12 11:45 UTC, bluewalk commented on README.md
> +
Agreed, the removal of NLog is more a thing that I use in my own projects as it has a different way of logging.
Furthermore this is basically my first pull request ever so I don't know if you can ignore the other changes beside the ones regarding the CentralScene ones?

2017-06-12 11:52 UTC, genielabs commented on README.md
> +
@bluewalk I think you create a new branch. Just add the *CentralScene* command class there and submit the PR. If you need other specific customizations that are not supposed to be merged in the master repo you can create other branches and sync with master whenever there are updates from the upstream.

2017-06-12 17:00 UTC, bluewalk commented
Will do as suggested. Will create new PR when ready!

2017-06-12 17:00 UTC, closed without merging

2017-12-18 04:16 UTC, kjetilpp commented
Any update?

2017-12-18 06:22 UTC, Bounz commented
Hi, @kjetilpp.
This was merged with PR #23.