Added CentralScene Command support
genielabs/zwave-lib-dotnet pull request #23
Opened 2017-06-12 17:12 UTC by bluewalk

Replacement for PR #15

2017-06-12 20:35 UTC, Bounz requested changes

2017-06-12 20:35 UTC, Bounz commented on ZWaveLib/Enums/Command.cs
> +        CentralSceneSet = 0x03,
According to documentation this commands should be named
- CentralSceneSupportedGet
- CentralSceneSupportedReport
- CentralSceneNotification

respectively (see SDS13781-2 "Z-Wave Application Command Class Specification" paragraph 4.16 at http://zwavepublic.com/specifications).

2017-06-12 20:35 UTC, Bounz commented on ZWaveLib/Values/CentralSceneValue.cs
> +    public enum CentralSceneValueID
This enum is not used anywhere in the library.
Do we need it?

2017-06-12 20:35 UTC, Bounz commented on ZWaveLib/Values/CentralSceneValue.cs
> +        Pressed1times = 0x0,
Please, rename to **Pressed1Time**

2017-06-12 20:35 UTC, Bounz commented on ZWaveLib/Values/CentralSceneValue.cs
> +        Pressed2times = 0x3,
Please, rename this and following enum values to Pressed2**T**imes.
Also, please be consistent in using byte values (you are mixing 0x3 with 0x**0**3 style). Let it be 0x**0**3.

2017-06-12 20:35 UTC, Bounz commented on ZWaveLib/Values/CentralSceneValue.cs
> +                keyAttribute -= 0x80;
This looks strange.
I think you have found that Fibaro Keyfob implements Central Scene Command Class V3, while you are implementing a mix of Central Scene Command Class V1 and V2.
In V3 there was introduced Slow Refresh flag in Central Scene Notification Command (see SDS13781-2 paragraph 4.17.7) which is the most significant bit, that's why you are subtracting the value of 0x80.
I think you should read Key Attribute from 3 least significant bits only.

2017-06-12 20:35 UTC, Bounz commented on ZWaveLib/Enums/EventParameter.cs
> +        CentralSceneCount,
Don't you mind to rename this to CentralSceneNotification and CentralSceneSupportedReport?

2017-06-12 20:35 UTC, Bounz commented on ZWaveLib/CommandClasses/CentralScene.cs
> +        public static ZWaveMessage Report(ZWaveNode node)
I don't think that we are going to send Central Scene Notifications from the controller.

2017-06-12 20:35 UTC, Bounz commented on ZWaveLib/CommandClasses/CentralScene.cs
> +        public static ZWaveMessage Get(ZWaveNode node)
It's better to rename this method to SupportedGet so it describes what this method actually do.

2017-06-13 04:07 UTC, bluewalk commented
I have implemented the requested changes into the PR

2017-06-13 14:28 UTC, Bounz approved these changes

2017-06-13 14:28 UTC, merged