Added Event timestamp
genielabs/zwave-lib-dotnet pull request #24
Opened 2017-06-12 17:18 UTC by bluewalk

Added timestamp to event (easier to determine the right event from picklists etc)

2017-06-12 19:08 UTC, ben-voss approved these changes

2017-06-12 20:57 UTC, Bounz requested changes
Hi.
Looks like you created this branch from your own CentralScene branch that's why we have here changed files from CentralScene also.
You can recreate this pull request using a branch that contains changes related to adding event timestamp only.

2017-06-13 03:57 UTC, bluewalk commented
Whoops, my bad, repushed the branch with only the TimeStamp changes.

2017-06-13 14:20 UTC, Bounz approved these changes

2017-06-13 14:20 UTC, merged